name: $(Date:yyyy.M.d)$(Rev:.r)
trigger:
  branches:
    include:
    - master

variables:
  MyConfiguration: Release
  MyPlatform: Any CPU
  WorkingDirectory: $(build.sourcesDirectory)\DevOpsTechChallenge
  WebSiteName: DevOpsTechChallenge.API

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: Build
  steps:
  - powershell: .\build.ps1 --Version '$(Build.BuildNumber)' --Configuration '$(MyConfiguration)'
    displayName: Run Nuke Build
    workingDirectory: $(WorkingDirectory)
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(WorkingDirectory)'
      failTaskOnFailedTests: true
      testRunTitle: 'Maples.Ping Build Tests'
      buildPlatform: '$(MyPlatform)'
      buildConfiguration: '$(MyConfiguration)'
  - task: PublishCodeCoverageResults@1
    displayName: Publish Coverage Results
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(WorkingDirectory)\**\in\**\coverage.cobertura.xml'
      pathToSources: '$(WorkingDirectory)'
  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: '$(WorkingDirectory)/$(WebSiteName).zip'
      artifact: 'WebSiteArtifact'
 